In [1]:
import numpy as np

### Checking the version of NumPy.

In [6]:
np.__version__

'2.3.4'

## Creating an array using NumPy.


In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr1[1]

np.int64(2)

In [9]:
arr2 = np.array([1, 2, 3, 4, 5], dtype=np.float16)
arr2

array([1., 2., 3., 4., 5.], dtype=float16)

### Checking the type of an array in NumPy.


In [10]:
type(arr2)

numpy.ndarray

In [15]:
arr2.dtype, arr1.dtype

(dtype('float16'), dtype('int64'))

## 0D-Array

In [16]:
zd_arr = np.array(20)
zd_arr

array(20)

In [17]:
zd_arr.ndim

0

## 1D-Array

In [19]:
oned_array = np.array([1, 5, 9, 7, 5, 3])
oned_array

array([1, 5, 9, 7, 5, 3])

In [20]:
oned_array.ndim

1

## 2D-array

In [22]:
twod_array = np.array([[1, 5, 9], [7, 5, 3]])
twod_array

array([[1, 5, 9],
       [7, 5, 3]])

In [23]:
twod_array.ndim

2

## 3D-Array

In [25]:
threed_array = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
threed_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
threed_array.ndim

3

## Defining an array with a specified dimension.


In [31]:
multid_array = np.array([1, 5, 9], ndmin=35)
multid_array

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,
                                         5,
                                         9]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [39]:
multid_array.ndim

35

# Access Array Elements

In [33]:
arr1[3]

np.int64(4)

In [36]:
twod_array[0][1], twod_array[0, 1]

(np.int64(5), np.int64(5))

In [40]:
threed_array[0][0][2], threed_array[0, 0, 2]

(np.int64(3), np.int64(3))