# Import NumPy

In [1]:
import numpy as np

#### Checking the version of NumPy.

In [2]:
np.__version__

'2.3.4'

## Creating an array using NumPy.


In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr1[1]

np.int64(2)

In [5]:
arr2 = np.array([1, 2, 3, 4, 5], dtype=np.float16)
arr2

array([1., 2., 3., 4., 5.], dtype=float16)

## Checking the type of an array in NumPy.


In [6]:
type(arr2)

numpy.ndarray

In [7]:
arr2.dtype, arr1.dtype

(dtype('float16'), dtype('int64'))

## 0D-Array

In [8]:
zd_arr = np.array(20)
zd_arr

array(20)

In [9]:
zd_arr.ndim

0

## 1D-Array

In [10]:
oned_array = np.array([1, 5, 9, 7, 5, 3])
oned_array

array([1, 5, 9, 7, 5, 3])

In [11]:
oned_array.ndim

1

## 2D-array

In [12]:
twod_array = np.array([[1, 5, 9], [7, 5, 3]])
twod_array

array([[1, 5, 9],
       [7, 5, 3]])

In [13]:
twod_array.ndim

2

## 3D-Array

In [14]:
threed_array = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
threed_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
threed_array.ndim

3

## Defining an array with a specified dimension.


In [16]:
multid_array = np.array([1, 5, 9], ndmin=35)
multid_array

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,
                                         5,
                                         9]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [17]:
multid_array.ndim

35

# Access Array Elements

In [18]:
arr1[3]

np.int64(4)

In [19]:
twod_array[0][1], twod_array[0, 1]

(np.int64(5), np.int64(5))

In [20]:
threed_array[0][0][2], threed_array[0, 0, 2]

(np.int64(3), np.int64(3))

## Array Slicing in Numpy

### Slicing 1-D arrays

In [21]:
arr = np.array([1,5,9,7,5,3])

In [22]:
arr[0:3]

array([1, 5, 9])

In [23]:
arr[0:-1]

array([1, 5, 9, 7, 5])

In [24]:
arr[2:]

array([9, 7, 5, 3])

In [25]:
arr[:6]

array([1, 5, 9, 7, 5, 3])

In [26]:
arr[0:6:2]

array([1, 9, 5])

In [27]:
arr[::3]

array([1, 7])

### Slicing 2-D arrays

In [28]:
arr2d = np.array([[1,5,9],[7,5,3]])

In [29]:
arr2d[1:3, : ]

array([[7, 5, 3]])

In [30]:
arr2d[ : , 1:3]

array([[5, 9],
       [5, 3]])

In [31]:
arr2d[1:3, 2]

array([3])